name: babymom_diary
description: "A Flutter app for tracking baby care activities"
publish_to: 'none'

version: 1.0.3+2

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.7
  go_router: ^15.1.2
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  cloud_functions: ^6.0.4
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_datetime_picker_plus: ^2.1.0
  widgetbook: ^3.7.0
  table_calendar: ^3.1.2
  rxdart: ^0.28.0
  fl_chart: ^0.68.0
  collection: ^1.18.0
  meta: ^1.15.0
  holiday_jp: ^0.0.8
  google_mobile_ads: ^5.3.1
  app_tracking_transparency: ^2.0.6
  cider: ^0.1.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.2
  home_widget: ^0.8.1
  app_links: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_cli: ^3.1.0
  mocktail: ^1.0.4
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/data/
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf

flutter_icons:
  image_path_android: assets/launcher_icon/milu_android_icon.png
  adaptive_icon_background: '#BD506A'
  adaptive_icon_foreground: assets/launcher_icon/milu_adaptive_foreground.png
  image_path_ios: assets/launcher_icon/milu_ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 30
  ios: true   

flutter_native_splash:
  image: "assets/launcher_icon/milu_android_transparent_icon.png"
  color: "#BD506A"
  android_12:
    image: "assets/launcher_icon/milu_android_transparent_icon.png"
    color: "#BD506A"
    icon_background_color: "#BD506A"
