name: bump

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Please Choice Bump Target
        options:
          - build
          - patch
          - minor
          - major

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: read flutter version from fvmrc
        id: fvm
        run: |
          FLUTTER_VERSION=$(cat flutter/.fvmrc | grep flutter | cut -d'"' -f4)
          echo "version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.version }}
          cache: true

      - name: run flutter version
        run: flutter --version
        working-directory: flutter

      - name: run flutter pub get
        run: flutter pub get
        working-directory: flutter

      - name: init git config
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL

      - name: bump up version
        run: |
          echo choice: ${{ github.event.inputs.bump }}
          flutter pub run cider bump ${{ github.event.inputs.bump }} --bump-build
          echo "BUMP_VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV
        working-directory: flutter

      - name: commit and push pubspec.yaml
        run: |
          git add -u flutter/pubspec.yaml
          echo "Bumped version number to $BUMP_VERSION" | git commit --file=-
          git push

      - name: create tag and release note
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh release create v$BUMP_VERSION --generate-notes
