name: deliver-android

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: read flutter version from fvmrc
        id: fvm
        run: |
          FLUTTER_VERSION=$(cat flutter/.fvmrc | grep flutter | cut -d'"' -f4)
          echo "version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

      - name: Create keystore file
        env:
          ANDROID_KEY_JKS_BASE64: ${{ secrets.ANDROID_KEY_JKS_BASE64 }}
        run: |
          echo $ANDROID_KEY_JKS_BASE64 | base64 --decode > flutter/android/app/upload.jks

      - name: Create key.properties file
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: |
          echo "storeFile=app/upload.jks" > flutter/android/key.properties
          echo "storePassword=$ANDROID_STORE_PASSWORD" >> flutter/android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> flutter/android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> flutter/android/key.properties

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.version }}
          cache: true

      - name: Run flutter version
        run: flutter --version
        working-directory: flutter

      - name: Create firebase_options_prod.dart
        env:
          FIREBASE_OPTIONS_PROD_BASE64: ${{ secrets.FIREBASE_OPTIONS_PROD_BASE64 }}
        run: |
          if [ -n "$FIREBASE_OPTIONS_PROD_BASE64" ]; then
            echo -n "$FIREBASE_OPTIONS_PROD_BASE64" | base64 --decode > flutter/lib/firebase_options_prod.dart
          else
            echo "Error: FIREBASE_OPTIONS_PROD_BASE64 secret not set"
            exit 1
          fi

      - name: Create google-services.json for Android
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          if [ -n "$GOOGLE_SERVICES_JSON_BASE64" ]; then
            echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > flutter/android/app/src/prod/google-services.json
          else
            echo "Error: GOOGLE_SERVICES_JSON_BASE64 secret not set"
            exit 1
          fi

      - name: Run flutter pub get
        run: flutter pub get
        working-directory: flutter

      - name: Get Version Number
        run: |
          echo "RELEASE_NAME=$(flutter pub run cider version | sed -E 's/([0-9.]+)\+([0-9]+)/\2(\1)/g')" >> $GITHUB_ENV
        working-directory: flutter

      - name: Build app bundle
        id: build
        run: flutter build appbundle --release --flavor prod --dart-define=FLAVOR=prod
        working-directory: flutter

      - name: Create google service account file
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 | base64 --decode > flutter/android/service-account.json

      - name: Upload to Google Play
        id: upload
        uses: r0adkll/upload-google-play@78c9e796b1035c94169c101d8e46cb880194bfc3
        with:
          releaseFiles: flutter/build/app/outputs/bundle/prodRelease/app-prod-release.aab
          serviceAccountJson: flutter/android/service-account.json
          packageName: com.aphlo.babymomdiary
          releaseName: ${{ env.RELEASE_NAME }}
          track: internal
          status: completed
